### ISSUE TITLE
Tip me this

### ISSUE THREAD

**Issue by puchunjie** [cssobj/cssobj-plugin-default-unit#1]
cssobj-plugin-default-unit.cjs.js:5 Uncaught TypeError: str.replace is not a function

**Comment by futurist** [comment]
Please post the code you're using. Seems the key is not a string type.

**Comment by puchunjie** [comment]
@futurist what difference between cssobj.js and cssobj-core.js
this my code :
`var` cssobj_core = require('cssobj-core')
`var` pluginUnit = require('cssobj-plugin-default-unit')
`var` cssobj = cssobj_core({plugins: [ pluginUnit('px') ]})
`var` resaut = cssobj(obj, {local:false})`

**Comment by futurist** [comment]
`cssobj-core` only render JS v-node, no output. `cssobj` will render v-node into browser's `<head>`, create a `<style>` tag.

Please show the `obj` your are using, in your above code.

**Comment by puchunjie** [comment]
@futurist thinks ,I solved it.  give you starts :)

**Comment by futurist** [comment]
Thank you!
